basePath: /api/v1/
definitions:
  handlers.changePasswordInput:
    properties:
      newPassword:
        type: string
      oldPassword:
        type: string
    type: object
  handlers.loginInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handlers.registerInput:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    type: object
  handlers.resetPasswordInput:
    properties:
      email:
        type: string
    type: object
  handlers.updateUserInput:
    properties:
      LastName:
        type: string
      firstName:
        type: string
    type: object
info:
  contact:
    email: songvut.nakrong@gmail.com
    name: Songvut Nakrong
  description: This is an API for Nihon Vocabulary Application
  title: Nihon Vocabulary
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login Form
        in: body
        name: loginInput
        required: true
        schema:
          $ref: '#/definitions/handlers.loginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Login
      tags:
      - Authentication
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: Register Form
        in: body
        name: registerInput
        required: true
        schema:
          $ref: '#/definitions/handlers.registerInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Register
      tags:
      - Authentication
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Reset Password
      parameters:
      - description: Reset Password Form
        in: body
        name: resetPasswordInput
        required: true
        schema:
          $ref: '#/definitions/handlers.resetPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Reset Password
      tags:
      - Authentication
  /user:
    delete:
      consumes:
      - application/json
      description: Delete User
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Delete User
      tags:
      - User
  /user/:
    get:
      consumes:
      - application/json
      description: Get User
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Get User
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update User
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Update User Form
        in: body
        name: updateUserInput
        required: true
        schema:
          $ref: '#/definitions/handlers.updateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Update User
      tags:
      - User
  /user/password:
    put:
      consumes:
      - application/json
      description: Update User
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Change Password Form
        in: body
        name: changePasswordInput
        required: true
        schema:
          $ref: '#/definitions/handlers.changePasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Change Password
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: ApiKeyAuth
    type: apiKey
swagger: "2.0"
